### ISSUE TITLE
Segmentation error with Python 3.10

### ISSUE THREAD

**Issue by a1ad** [borgbase/vorta#1094]
Segmentation error when trying to start Vorta.

- OS: Fedora 35 Gnome 41
- Vorta version: 0.7.8
- Borg: 1.1.17
- Installed from: repo or pip

Logs:

```
$ vorta
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
2021-11-02 14:50:36,741 - vorta.i18n - DEBUG - Loading translation succeeded for ['nl-BE', 'nl-Latn-BE'].
2021-11-02 14:50:36,744 - apscheduler.scheduler - INFO - Scheduler started
2021-11-02 14:50:36,842 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-11-02 14:50:36,903 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
Segmentatiefout (geheugendump gemaakt)

```

**Comment by bastiencyr** [comment]
Hello @a1ad ,
Can you open a terminal and run the command `borg --version` ?

**Comment by a1ad** [comment]
? You can see the Borg version in my initial post.

**Comment by bastiencyr** [comment]
> ? You can see the Borg version in my initial post.

Yes but it's not to see your borg version, it's to check if the seg fault doesn't come from borg. 

You can also try this command: 
`QT_QPA_PLATFORM=xcb vorta`

**Comment by m3nu** [comment]
Yeah, this error happens in Qt, not Python. And since there is no Python error we can address, we can't do too much about this error without further details. I can only try to reprod this on a VM and hope it happens again.

**Comment by jardev** [comment]
Same for me. Stopped working with the same error after upgrading from Fedora 34 to Fedora 35. borg version is 1.1.17. 
`QT_QPA_PLATFORM=xcb vorta` did not help.
```
❯  QT_QPA_PLATFORM=xcb vorta
2021-11-03 23:22:51,601 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2021-11-03 23:22:51,608 - apscheduler.scheduler - INFO - Scheduler started
2021-11-03 23:22:51,609 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-11-03 23:22:51,609 - vorta.scheduler - DEBUG - New job for profile Default was added.
2021-11-03 23:22:51,774 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-11-03 23:22:51,844 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/qt.py", line 47, in _process_jobs
    self._start_timer(wait_seconds)
  File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/qt.py", line 34, in _start_timer
    self._timer = QTimer.singleShot(wait_time, self._process_jobs)
TypeError: arguments did not match any overloaded call:
  singleShot(int, PYQT_SLOT): argument 1 has unexpected type 'float'
  singleShot(int, Qt.TimerType, PYQT_SLOT): argument 1 has unexpected type 'float'
2021-11-03 23:22:51,855 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
[1]    21116 segmentation fault (core dumped)  QT_QPA_PLATFORM=xcb vorta
```
Looks like it needs some updates regarding Qt or maybe a 3rd-party dependency (e.g. `apscheduler`)?

**Comment by bastiencyr** [comment]
Yes apscheduler is out of date. See this issue : https://github.com/borgbase/vorta/issues/1083 

> QT_QPA_PLATFORM=xcb vorta did not help. 

At least, there is an error, if you remove QT_QPA_PLATFORM=xcb vorta, is there a different error ? If yes, it means that there is some issue with wayland. In any case, there is issue with apscheduler.

**Comment by jardev** [comment]
> At least, there is an error, if you remove QT_QPA_PLATFORM=xcb vorta, is there a different error ? If yes, it means that there is some issue with wayland. In any case, there is issue with apscheduler.

The output is a bit different but the stack trace is the same at the end:
```
❯ vorta
QSocketNotifier: Can only be used with threads started with QThread
2021-11-04 08:08:19,947 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2021-11-04 08:08:19,956 - apscheduler.scheduler - INFO - Scheduler started
2021-11-04 08:08:19,958 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-11-04 08:08:19,959 - vorta.scheduler - DEBUG - New job for profile Default was added.
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
2021-11-04 08:08:20,143 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
2021-11-04 08:08:20,231 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/qt.py", line 47, in _process_jobs
    self._start_timer(wait_seconds)
  File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/qt.py", line 34, in _start_timer
    self._timer = QTimer.singleShot(wait_time, self._process_jobs)
TypeError: arguments did not match any overloaded call:
  singleShot(int, PYQT_SLOT): argument 1 has unexpected type 'float'
  singleShot(int, Qt.TimerType, PYQT_SLOT): argument 1 has unexpected type 'float'
2021-11-04 08:08:20,236 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
[1]    52622 segmentation fault (core dumped)  vorta
```

**Comment by jardev** [comment]
I temporarily patched my local `/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/qt.py` and changed the following at line 33 from:
```
           wait_time = min(wait_seconds * 1000, 2147483647)
```
to:
```
           wait_time = int(min(wait_seconds * 1000, 2147483647))
```
and then started Vorta again but got another error:
```
❯ vorta
QSocketNotifier: Can only be used with threads started with QThread
2021-11-04 08:44:38,608 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2021-11-04 08:44:38,615 - apscheduler.scheduler - INFO - Scheduler started
2021-11-04 08:44:38,616 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-11-04 08:44:38,617 - vorta.scheduler - DEBUG - New job for profile Default was added.
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
2021-11-04 08:44:38,790 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
2021-11-04 08:44:38,889 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
[1]    54568 segmentation fault (core dumped)  vorta
```

**Comment by jardev** [comment]
and then after patching the `apscheduler` if I run Vorta with `QT_QPA_PLATFORM=xcb vorta` I get the following:
```
❯ QT_QPA_PLATFORM=xcb vorta
2021-11-04 08:49:58,682 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2021-11-04 08:49:58,688 - apscheduler.scheduler - INFO - Scheduler started
2021-11-04 08:49:58,690 - apscheduler.scheduler - INFO - Added job "VortaScheduler.create_backup" to job store "default"
2021-11-04 08:49:58,690 - vorta.scheduler - DEBUG - New job for profile Default was added.
2021-11-04 08:49:58,865 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-11-04 08:49:58,962 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
[1]    54775 segmentation fault (core dumped)  QT_QPA_PLATFORM=xcb vorta
```

**Comment by jardev** [comment]
And a stack trace from the system log:
```
#0  0x00007f2e675b916d type_call (libpython3.10.so.1.0 + 0x11216d)
#1  0x00007f2e675b8fb4 _PyObject_MakeTpCall (libpython3.10.so.1.0 + 0x111fb4)
#2  0x00007f2e675aa920 _PyObject_CallFunctionVa (libpython3.10.so.1.0 + 0x103920)
#3  0x00007f2e675aa653 PyObject_CallFunction (libpython3.10.so.1.0 + 0x103653)
#4  0x00007f2e58c59ae2 meth_QEvent_type.lto_priv.0 (QtCore.abi3.so + 0x1afae2)
#5  0x00007f2e675bd3d8 cfunction_call (libpython3.10.so.1.0 + 0x1163d8)
#6  0x00007f2e675b8fb4 _PyObject_MakeTpCall (libpython3.10.so.1.0 + 0x111fb4)
#7  0x00007f2e675b5c8d _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x10ec8d)
#8  0x00007f2e675aee44 _PyEval_Vector (libpython3.10.so.1.0 + 0x107e44)
#9  0x00007f2e675c598e method_vectorcall (libpython3.10.so.1.0 + 0x11e98e)
#10 0x00007f2e55cceb9a call_method (sip.cpython-310-x86_64-linux-gnu.so + 0x16b9a)
#11 0x00007f2e55ccedcd sip_api_call_method.lto_priv.0 (sip.cpython-310-x86_64-linux-gnu.so + 0x16dcd)
#12 0x00007f2e549d3ded _Z17sipVH_QtWidgets_416PyGILState_STATEPFvP17_sipSimpleWrapperS_ES1_P7_objectP7QObjectP6QEvent (QtWidgets.abi3.so + 0x161ded)
#13 0x00007f2e54c07a5b _ZN15sipQApplication11eventFilterEP7QObjectP6QEvent (QtWidgets.abi3.so + 0x395a5b)
#14 0x00007f2e587c344f _ZN23QCoreApplicationPrivate34sendThroughApplicationEventFiltersEP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a644f)
#15 0x00007f2e54313480 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x1ae480)
#16 0x00007f2e54c0c7e6 _ZN15sipQApplication6notifyEP7QObjectP6QEvent (QtWidgets.abi3.so + 0x39a7e6)
#17 0x00007f2e587c3798 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a6798)
#18 0x00007f2e587c6d06 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2a9d06)
#19 0x00007f2e588150d7 _ZL23postEventSourceDispatchP8_GSourcePFiPvES1_ (libQt5Core.so.5 + 0x2f80d7)
#20 0x00007f2e57b9e33f g_main_context_dispatch (libglib-2.0.so.0 + 0x5533f)
#21 0x00007f2e57bf32b8 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa2b8)
#22 0x00007f2e57b9b9e3 g_main_context_iteration (libglib-2.0.so.0 + 0x529e3)
#23 0x00007f2e58814b78 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7b78)
#24 0x00007f2e587c21a2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51a2)
#25 0x00007f2e587ca6e4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2ad6e4)
#26 0x00007f2e54c0f07e meth_QApplication_exec.lto_priv.0 (QtWidgets.abi3.so + 0x39d07e)
#27 0x00007f2e675bd3d8 cfunction_call (libpython3.10.so.1.0 + 0x1163d8)
#28 0x00007f2e675b8fb4 _PyObject_MakeTpCall (libpython3.10.so.1.0 + 0x111fb4)
#29 0x00007f2e675b5c8d _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x10ec8d)
#30 0x00007f2e675aee44 _PyEval_Vector (libpython3.10.so.1.0 + 0x107e44)
#31 0x00007f2e675aff7e _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x108f7e)
#32 0x00007f2e675aee44 _PyEval_Vector (libpython3.10.so.1.0 + 0x107e44)
#33 0x00007f2e67629e24 PyEval_EvalCode (libpython3.10.so.1.0 + 0x182e24)
#34 0x00007f2e67659bb4 run_eval_code_obj (libpython3.10.so.1.0 + 0x1b2bb4)
#35 0x00007f2e676550d6 run_mod (libpython3.10.so.1.0 + 0x1ae0d6)
#36 0x00007f2e6752ca3c pyrun_file.cold (libpython3.10.so.1.0 + 0x85a3c)
#37 0x00007f2e6764f792 _PyRun_SimpleFileObject (libpython3.10.so.1.0 + 0x1a8792)
#38 0x00007f2e6764f527 _PyRun_AnyFileObject (libpython3.10.so.1.0 + 0x1a8527)
#39 0x00007f2e6764c664 Py_RunMain (libpython3.10.so.1.0 + 0x1a5664)
#40 0x00007f2e6761afed Py_BytesMain (libpython3.10.so.1.0 + 0x173fed)
#41 0x00007f2e672ca560 __libc_start_call_main (libc.so.6 + 0x2d560)
#42 0x00007f2e672ca60c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d60c)
#43 0x000055b8c960b095 _start (python3.10 + 0x1095)
```

**Comment by m3nu** [comment]
APScheduler doesn't work with Python 3.10. We already removed it in the current master branch. So if your OS is also very new, you need to use the current master branch, which works well on Python 3.10 and doesn't use APScheduler at all.

**Comment by m3nu** [comment]
I should probably do a small PyPi release that blocks 0.7 from running on Python 3.10

**Comment by m3nu** [comment]
I've released the changes we already have as v0.8.0 pre-release. This should take care of the issues here. Also added to PyPi:

https://github.com/borgbase/vorta/releases/tag/v0.8.0

**Comment by jardev** [comment]
I installed the development version with `pip` as following:
```
$ pip install --user git+https://github.com/borgbase/vorta#egg=vorta
```
It's 0.8.0:
```
❯ vorta --version
Vorta 0.8.0
```
Yet it's still crashing after a while:
```
❯ vorta
QSocketNotifier: Can only be used with threads started with QThread
2021-11-04 13:34:39,712 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
2021-11-04 13:34:39,875 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
2021-11-04 13:34:39,952 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2021-11-04 13:34:40,251 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2021-11-04 13:34:40,253 - vorta.scheduler - INFO - Setting timer for profile 1
2021-11-04 13:34:40,253 - vorta.scheduler - DEBUG - Scheduling next run for 2021-11-04 15:00:00
[1]    71104 segmentation fault (core dumped)  vorta
```
And also with `QT_QPA_PLATFORM=xcb`:
```
❯ QT_QPA_PLATFORM=xcb vorta
2021-11-04 13:37:26,155 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2021-11-04 13:37:26,300 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-11-04 13:37:26,378 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2021-11-04 13:37:26,745 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2021-11-04 13:37:26,760 - vorta.scheduler - INFO - Setting timer for profile 1
2021-11-04 13:37:26,764 - vorta.scheduler - DEBUG - Scheduling next run for 2021-11-04 15:00:00
[1]    71243 segmentation fault (core dumped)  QT_QPA_PLATFORM=xcb vorta
```
It starts but then crashes a few seconds later.

**Comment by m3nu** [comment]
Thanks for testing. Will try to reproduce this one locally first.

**Comment by melianmiko** [comment]
Same problem on Fedora 35.
`QT_QPA_PLATFORM=xcb` already set in `.profile`.

![image](https://user-images.githubusercontent.com/67851274/140502000-041ecdd1-fc42-410d-9667-9ec359404b95.png)
![image](https://user-images.githubusercontent.com/67851274/140501823-0bf3ca2a-8848-4c24-8b52-526a5696dd7c.png)

**Comment by m3nu** [comment]
I can reprod the issue. It happens when using `QThread` or `QThreadpool`. It does NOT happen with Python's own `threading.Thread`. Looking into changing the threading library.

**Comment by bastiencyr** [comment]
> I can reprod the issue. It happens when using `QThread` or `QThreadpool`. It does NOT happen with Python's own `threading.Thread`. Looking into changing the threading library.

Oh... This implies consequent changes, maybe we can open an issue on pyqt repo. In any case, it seems that you can assign this migration to myself, let me know if you are sure.

**Comment by m3nu** [comment]
Here a first draft. Also works on Fedora 35. Let's discuss the details in the PR, @bastiencyr 

https://github.com/borgbase/vorta/pull/1096
