### ISSUE TITLE
Translation missing on "Extract" dialog for grid columns and "Extract" button.

### ISSUE THREAD

**Issue by delfino-nunez** [borgbase/vorta#1242]
**Describe the bug**
The "Extract" dialog grid columns are not translated and the "Extract" button is not translated also.

**To Reproduce**
1. Go to 'Archives'
2. Select an archive from the list
3. Click on 'Extract'
4. See untranslated strings

![Selection_003](https://user-images.githubusercontent.com/770967/160532144-a36ba806-e3ed-4ec6-a83c-a9d4b771d4c3.png)

**Environment (please complete the following information):**
- OS: Linux 5.13.0-37-generic # 42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Vorta version: 0.8.3
- Installed from: GitHub repo

**Comment by real-yfprojects** [comment]
The missing translation of the extract button is already fixed. But maybe it hasn't been translated on transifex yet.

**Comment by delfino-nunez** [comment]
You are right, I see it in the code but is still not in transifex. I'll wait for that to be generated.
Thanks.

![Selection_005](https://user-images.githubusercontent.com/770967/160537165-8034cca0-0e8c-4ad3-ae29-fba9c31b8933.png)

**Comment by real-yfprojects** [comment]
> You are right, I see it in the code but is still not in transifex. I'll wait for that to be generated. Thanks.

@m3nu Can you push the new source strings to transifex?

**Comment by delfino-nunez** [comment]
Thank you for pushing the strings.

I've create PR #1244, not sure if that the right way to solve this one.

**Comment by real-yfprojects** [comment]
> Added you as maintainer and will push shortly. smile

Great! I can now update the source strings myself - and change the settings which I will only do in consultation with you which is what I will do in the following. 

There is an option for transifex projects to translate duplicates automatically. This would save quite some work I think and foster consistency, but might lead to wrong translations if the same string is used in different contexts.

**Comment by m3nu** [comment]
> There is an option for transifex projects to translate duplicates automatically. This would save quite some work I think and foster consistency, but might lead to wrong translations if the same string is used in different contexts.

Feel free to enable it and whatever else makes sense.

**Comment by real-yfprojects** [comment]
Fixed in d8e4a93cdd527b692869da0969c0fbf43f08305d.
