### ISSUE TITLE
Extract: some duplicate entries are shown

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#217]
After extracting my latest backup archive, I see (at least here) duplicate entries:

![grafik](https://user-images.githubusercontent.com/1151915/53693050-81982300-3d9a-11e9-8fe7-b7184357b119.png)

**Comment by m3nu** [comment]
This I can't reproduce. What does the output of this Borg command say:

`borg list --info --log-json --format {size:8d}{TAB}{mtime}{TAB}{path}{NL} $REPO_PATH::$ARCHIVE_NAME`

The tree is parsed from that list, so it can get a bit long. If you post it here, you can redact sensitive folders.

**Comment by Wikinaut** [comment]
After extracting the same archive again, I have even more:

![grafik](https://user-images.githubusercontent.com/1151915/53693188-4ba86e00-3d9d-11e9-8f2e-6d71597c1e06.png)

**Comment by Wikinaut** [comment]
I closed and restarted Vorta.

Now
![grafik](https://user-images.githubusercontent.com/1151915/53693228-c1acd500-3d9d-11e9-82d7-a93724ca73e0.png)
there is an empty name directory:

![grafik](https://user-images.githubusercontent.com/1151915/53693238-e608b180-3d9d-11e9-9710-b6f0e71e8885.png)

**Comment by Wikinaut** [comment]
I have only one clue: Yesterday I experimented with Vorta an **mounted** an archive (FUSE) to /work/borg . Thereafter I did my many backups, **very** likely I forgot to umount the /work/borg FUSE path before starting my real backups which later also included /work.

Today I found remains of that in my root.

it may be, that the FUSE mount /work/borg introduces some spooky things.

**Comment by Wikinaut** [comment]
I run

```borg list --info --log-json --format {size:8d}{TAB}{mtime}{TAB}{path}{NL} $REPO_PATH::$ARCHIVE_NAME > borg.lst```

and could **not** find any duplicates in the output using 

``` sort borg.lst | uniq -d```

**Comment by m3nu** [comment]
Ah. I know what's happening. I didn't overwrite the global file list in the rushed PR before.

**Comment by m3nu** [comment]
Fixed in #217. Shouldn't rush PRs without long testing really.

**Comment by Wikinaut** [comment]
Just a question: I installed vorta using "pip". When you now update the code, what's the recommended way to follow your changes quickly, should I deinstall the pipped script and turn to git?

**Comment by Wikinaut** [comment]
I still have this issue:

![grafik](https://user-images.githubusercontent.com/1151915/53693635-8b725400-3da3-11e9-91d6-15906713e099.png)

**Comment by m3nu** [comment]
What does the output of this Borg command say:

`borg list --info --log-json --format {size:8d}{TAB}{mtime}{TAB}{path}{NL} $REPO_PATH::$ARCHIVE_NAME`

The tree is parsed from that list, so it can get a bit long. If you post it here, you can redact sensitive folders.

**Comment by Wikinaut** [comment]
@m3nu I don't want to upload this list in clear and currently thinking of a way to programmatically simply hash the entries.

**Comment by m3nu** [comment]
You can just look which parent folder is displayed for those subfolders (with the empty parent folder).

If this was a mounted repo, I would expect many weird things to happen.

**Comment by Wikinaut** [comment]
Hmm, just as a quick result: nothing specific found:

I took a specific filename pattern of files in one the "doublure" folders as example,. let's say ```/home/1/xxxpattern```, where such files are also shown in Vorta in the spooky folder ```empty/home/1/xxxpattern```.

Checking directly in the filenlist
```grep xxxpattern borg.lst``` only gives the correct pathname, only once.

**Comment by m3nu** [comment]
Without a sample file, I'll have to reproduce this issue. What are the steps to trigger the issue?

**Comment by Wikinaut** [comment]
@m3nu I found a very few filenames which had cluttered the borg(!) output file by adding newlines 
coming out of the filename, so that that single file consumes more than one line in the borg list output.

So I think, I have to report this "upstream" to Borg. Will do so later.

Here is one of these filenames: (xxx, yyyy, tttt -> redacted content)

```
234973        Wed, 2015-11-04 17:03:22        home/xxx/yyy/tttttt tttttt ttttttttt
ttttttttttttttttt tttttttttttttttt
ttttt tttt ttttt
  tttt ttttt ttt.pdf
```

**Comment by m3nu** [comment]
Roughly what I expected. The question is if Borg should deal with it, if the file system provides those file names.

**Comment by Wikinaut** [comment]
@m3nu These filenames have clearly one or more single `0x0A` bytes in it, which apparently breaks ```borg list``` output. 

At the moment, I repair these filenames on my computer and will then run a Vorta/Borg update to see if these solves the "duplicate entries" issue. I will report here later.

**Comment by Wikinaut** [comment]
@m3nu apart from the ```0x0a``` issue - I don't have any files any more with these byte -, I have found the following in my ```borg list``` output:

There are three suspicious entries:
```
(date) work
(date) work/xxx
...
(date) etc
(date) etc/yyyy
....
(date) opt
(date) opt/firefox
```

What I mean is:
these three toplevel entries appear to have no ```/``` characters in the list. Perhaps this breaks your Vorta parsing.

This is the (current) list of my sources-to-be-backuped
![grafik](https://user-images.githubusercontent.com/1151915/53700008-593a1400-3dee-11e9-85ad-d444f514b252.png)

**Comment by Wikinaut** [comment]
@m3nu for your information: https://github.com/borgbackup/borg/issues/4421

**Comment by Wikinaut** [comment]
@m3nu 
* I changed all "offending" filenames on my computer and created a new borg backup archive.
* I made a fresh backup using these rules:

image 1
![grafik](https://user-images.githubusercontent.com/1151915/53732258-a913ec00-3e7d-11e9-8861-9421e50b509b.png)

* clicking on "Extrahieren" again results in a wrong display (with the "empty" root directory name, wherein again these subfolder live, image 3):
image 2
![grafik](https://user-images.githubusercontent.com/1151915/53732346-f6905900-3e7d-11e9-9637-332bd08bfc72.png)

image 3
![grafik](https://user-images.githubusercontent.com/1151915/53732370-0740cf00-3e7e-11e9-8ac2-752e043619f5.png)

**Comment by m3nu** [comment]
Hard to comment on this without seeing the input file. Is this with PR #219?

**Comment by Wikinaut** [comment]
@m3nu negative. I applied the three files from #219 , restarted of course, result is the same
![grafik](https://user-images.githubusercontent.com/1151915/53760451-3299dd00-3ec3-11e9-90a2-c03b0cace037.png)

**Comment by m3nu** [comment]
The PR was about duplicate entries due to not clearing the list of file names.

I don't have a solution for dealing with extra line breaks or tabs in file names. Any additional check in parsing the file list could slow things down. Could be easier to use other control chars in the list itself:

`--format {size:8d}{TAB}{mtime}{TAB}{path}{NL}`
