### ISSUE TITLE
Segfault when closing from tray

### ISSUE THREAD

**Issue by SamuelBenard** [borgbase/vorta#456]
**Describe the bug**
When I close vorta, I get an error message : Erreur de segmentation (core dumped)
(seg fault (core dumped) )

**To Reproduce**
Start vorta from command line : $ /home/username/.local/bin/vorta
Right click icon in systray and choose "Close"
Look at the console, you have an error message

**Desktop (please complete the following information):**
System:    Kernel: 5.3.0-51-generic x86_64 bits: 64 compiler: gcc 
           v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

**Additional context**
syslog : 
May 15 15:10:45  kernel: [789665.809030] vorta[7740]: segfault at 8 ip 00007f0b10a712e7 sp 00007fff415defa0 error 4 in libQt5Widgets.so.5[7f0b108d4000+62c000]
May 15 15:10:45  kernel: [789665.809055] Code: ef e8 3d 3b fd ff e9 61 fe ff ff 0f 1f 84 00 00 00 00 00 f6 40 09 80 0f 84 0e fe ff ff 48 8b 05 77 c3 6b 00 48 89 ee 48 8b 00 <48> 8b 78 08 e8 30 c2 fc ff e9 f3 fd ff ff 0f 1f 00 49 8b 77 10 48
May 15 15:10:45  systemd[1]: Started Process Core Dump (PID 7753/UID 0).
May 15 15:10:46  systemd-coredump[7754]: Process 7740 (vorta) of user 1000 dumped core.#012#012Stack trace of thread 7740:#012#0  0x00007f0b10a712e7 n/a (/home/username/.local/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5)

**Comment by m3nu** [comment]
This error happens in Qt, so I'm not sure we can help here. Maybe try to reproduce a minimal sample and file with them?

Vorta also doesn't have a right-click menu or a "Close" item. We only have "Quit" in our menu. Maybe close is from the OS and send some other signal to the app?

**Comment by SamuelBenard** [comment]
here's a screen shot of the right click menu on the systray icon. Sorry, it's french but it says : 

- Vorta for borgBackup
- Next task : none scheduled (greyed)
- Backup now
- Close

https://imgur.com/a/WGJH6aQ

Actually, I can reproduce it everytime. I can file a bugreport at Qt. they'll probably tell me that they have no idea what's the problem as they don't know how vorta is coded. Anyway, if you think it's not vorta related, feel free to close the bug

**Comment by m3nu** [comment]
I don't work on a Linux desktop and can't do any testing on this.

Maybe @Hofer-Julian wants to try, but I feel bad passing him all the Linux stuff.

**Comment by SamuelBenard** [comment]
I can do tests if needed

**Comment by m3nu** [comment]
Thanks. When looking at the code we only call Qt's `QApplication.quit()` method. So nothing happens in Vorta at all.

```
        exit_action = menu.addAction(self.tr('Quit'))
        exit_action.triggered.connect(self.app.quit)
```

**Comment by SamuelBenard** [comment]
I tried this : https://stackoverflow.com/questions/2663841/python-tracing-a-segmentation-fault (first answer).
Added the "def trace" function in my vorta script just after the imports and `sys.settrace(trace)` just after function def.
Then runned vorta and closed the app. 
it gave me millions of lines, i'll just copy here the last few lines
`return, /usr/lib/python3.6/multiprocessing/util.py:268
return, /usr/lib/python3.6/multiprocessing/util.py:322
call, /home/samuel/.local/lib/python3.6/site-packages/paramiko/transport.py:119
line, /home/samuel/.local/lib/python3.6/site-packages/paramiko/transport.py:120
return, /home/samuel/.local/lib/python3.6/site-packages/paramiko/transport.py:120
Erreur de segmentation (core dumped)
`

Looks like it crashes on this function : 
`def _join_lingering_threads():
    for thr in _active_threads:
        thr.stop_thread()
`

I can add breakpoints and show variables if you want (I don't know python but I can past code ;) )

**Comment by SamuelBenard** [comment]
After some more search, the problem is not related to _join_lingering_threads.

Could it be related to http://bugs.python.org/issue1856 ?

I tried this https://stackoverflow.com/questions/18098475/detect-interpreter-shut-down-in-daemon-thread

but parent_thread is not defined. I'm probably missing something but have not idea what.

**Comment by m3nu** [comment]
I couldn't reproduce this on Debian Testing or macOS 10.15.5. Is this still an issue?

**Comment by SamuelBenard** [comment]
Afaic, still an issue

I launch vorta from prompt , right click on systray icon and click 'close'

`$ vorta --version
Vorta 0.6.24
$ vorta
2020-06-02 12:32:12,228 - vorta.i18n - DEBUG - Loading translation succeeded for ['fr', 'fr-FR', 'fr-Latn-FR'].
2020-06-02 12:32:12,246 - apscheduler.scheduler - INFO - Scheduler started
2020-06-02 12:32:12,270 - qdarkstyle - DEBUG - Reading QSS file in: :qdarkstyle/style.qss
2020-06-02 12:32:12,271 - qdarkstyle - INFO - QSS file sucessfuly loaded.
2020-06-02 12:32:12,271 - qdarkstyle - DEBUG - Checking patches for being applied.
2020-06-02 12:32:12,271 - qdarkstyle - INFO - Found application patches to be applied.
2020-06-02 12:32:12,683 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
Erreur de segmentation (core dumped)

`

**Comment by m3nu** [comment]
You can try updating Qt and PyQt to version <5.15 (we had issues with Qt 5.15, released a few days ago) and use the current master branch, which removes some style hacks. Since the error doesn't happen in Python, it's probably in Qt. Roughly:

```
$ git clone https://github.com/borgbase/vorta
$ cd vorta && pip3 install -U .
```

**Comment by m3nu** [comment]
It's not related to French translations. Just tested that.

**Comment by SamuelBenard** [comment]
Sorry

`$ vorta --version
Vorta 0.6.26
$ vorta
2020-06-02 14:09:55,874 - vorta.i18n - DEBUG - Loading translation failed for ['fr', 'fr-FR', 'fr-Latn-FR'].
2020-06-02 14:09:55,891 - apscheduler.scheduler - INFO - Scheduler started
2020-06-02 14:09:56,272 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
Erreur de segmentation (core dumped)
`

**Comment by m3nu** [comment]
We don't do anything special when you "Quit" the app. So probably not an issue if it crashes. Still a bit weird.

**Comment by SamuelBenard** [comment]
Yes I know you don't do anything special on quit. If you want me to do some more test, feel free. I can open an issue on Qt's bug report. Should I send them the first post I posted here ?

**Comment by m3nu** [comment]
Don't worry. They would probably need a minimal reproducible sample app first. Like a mini app that crashes as well.

I'll be back, if I can think of anything.

**Comment by SamuelBenard** [comment]
mini app and environment as it seems to crash only in my situation. Maybe I can try to make a virtualbox machine with my configuration ? I remove everything that's not needed ?

**Comment by m3nu** [comment]
That would be a bit of work. I'd look into Qt first. The logs from your first comment all point to Qt.

`/home/username/.local/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5`

You could also try with Python 3.7. And make really sure Qt is at the latest 5.14.x version.

**Comment by SamuelBenard** [comment]
```shell
Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
```
I don't know if I can easily install newer version

```shell
$ python3 --version
Python 3.6.9
```

**Comment by m3nu** [comment]
Qt 5.9 is very very old. Around 2017. I'd definitely try to update that first.

**Comment by SamuelBenard** [comment]
Next version of mint (this month hopefully) should be based on Ubuntu 20.04 and have Qt 5.12.5

**Comment by sandrotosi** [comment]
BTW this is still happening with vorta/0.7.1 on an up-to-date debian unstable

**Comment by samuel-w** [comment]
Please post your logs and terminal output.

**Comment by sandrotosi** [comment]
there's really no output: just "Segmentation fault", i've run a gdb if that's helpful (here attached)
[vorta_sigsegv_gdb.txt](https://github.com/borgbase/vorta/files/5742754/vorta_sigsegv_gdb.txt)

where can i find the logs?

**Comment by samuel-w** [comment]
Click the logs button in the misc tab.

**Comment by sandrotosi** [comment]
there's nothing in the log regarding the crash, which is happening on close (so that's kinda expected)

**Comment by samuel-w** [comment]
What's your Qt version?

**Comment by sandrotosi** [comment]
5.15.2

**Comment by samuel-w** [comment]
Try using the flatpak version.

**Comment by m3nu** [comment]
You also get a stacktrace when running Vorta from the command line directly. Just `$ vorta` after installing with PyPi.

But as mentioned above, if the segfault is in Qt, we can't do much about it. If it's in Python, it will print a stacktrace and we can look into it.

Flathub may help you too, as it's a controlled env.

**Comment by sandrotosi** [comment]
there is no traceback on the command-line, it's just "Segmentation fault"

i understand it crashes inside Qt, but no other application using Qt is crashing, so it looks to me as if vorta is doing something that's not supposed to, and Qt SIGSEGV.

I'm afraid i am not going to use the flatpak

**Comment by m3nu** [comment]
Possible. If you find the reason, let us know here or open a pull request with the change.

**Comment by sandrotosi** [comment]
I just wanted to make sure this bug is updated so that people are aware it's still happening; it's unlikely i will spend time debugging it further (but i'm open to run commands/tests as directed by you)

**Comment by sten0** [comment]
Hi @m3nu, I took a look at this, to try to map out the conditions that trigger it.

1. First run, open Vorta, close from tray, no SIGSEGV.
2. First run, open Vorta, initialise repo, close from tray, no SIGSEGV.
3. First run, open Vorta, initialise repo, create archive, close from tray, no SIGSEGV.
4. Second run, open Vorta, do nothing, close from tray, SIGSEGV.
5. All subsequent runs, open Vorta, do any actions, close from tray, SIGSEGV.

I'm going to contact the Debian Qt/KDE Team for help debugging.  Given that first run vs subsequent run appears to be the trigger condition, I'm not sure that it's purely a PyQt5 issue.

**Comment by sten0** [comment]
Oh, and by "subsequent runs", I mean "post repo initialisation"

**Comment by sandrotosi** [comment]
for me, it does SIGSEGV even without performing any action (but with a registered profile and repository): open vorta, right click on the traybar icon, Quit, SIGSEGV

**Comment by m3nu** [comment]
This is a known Qt issue. It happens on Fedora, but not Ubuntu and macOS. Not sure we should address it.

https://www.riverbankcomputing.com/static/Docs/PyQt5/gotchas.html#crashes-on-exit

**Comment by SamuelBenard** [comment]
> This is a known Qt issue. It happens on Fedora, but not Ubuntu and macOS. Not sure we should address it

As said in the fist post,  i had the issue with linux mint 19.03 which is based on ubuntu 18.04

**Comment by m3nu** [comment]
The Ubuntu I have here is Kubuntu 20.20 with PyQt 5.15.2.

There are reports that the issue can be avoided by deleting all Qt objects before quitting. Problem is we have a *lot* of them. PyQt added an optional fix in 5.12?? Not sure if they made it permanent yet.

**Comment by sten0** [comment]
Manu <notifications@github.com> writes:

> The Ubuntu I have here is Kubuntu 20.20 with PyQt 5.15.2.
>
> There are reports that the issue can be avoided by deleting all Qt objects before quitting. Problem is we have a *lot* of them. PyQt added an optional fix in 5.12?? Not sure if they made it permanent yet.
>

Sandro Tosi reported this bug in Debian, and he was also using PyQt
5.15.2.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978105

I will ask some colleagues what they recommend.  If there's no way that
this issue is causing the test failures at #748, then I'd like to cherry
pick the eventual fix at a later date and skip it for 0.7.3.

Please ping me if I don't provide more info by 22 or 23 Feb.

Thanks,
Nicholas

**Comment by m3nu** [comment]
I believe this is fixed in #877. Also responded to the Debian bug.

**Comment by m3nu** [comment]
This should be fixed in the current `master` branch and will be released as 0.7.4.

Would appreciate feedback is your reported bug here is addressed.

**Comment by m3nu** [comment]
I believe this is now fully fixed via #898. The trick was to remove the system tray widget before closing the app.

**Comment by sandrotosi** [comment]
i'm afraid this is still happening, although with a different combination of operations:

1. open vorta
2. create a new profile (just enter the name and exit)
3. close vorta
4. SIGSEGV

**Comment by m3nu** [comment]
Right. Can reproduce it. It's a related issue and happens when the opened dialog isn't deleted properly.

Deleting it when closing the app didn't work reliably, but setting `self.setAttribute(QtCore.Qt.WA_DeleteOnClose)` worked. PR: #922 This should fix it for all our dialogs.

**Comment by sten0** [comment]
>> Sandro Tosi ***@***.***> writes:
>>
>> i'm afraid this is still happening, although with a different combination of operations:
>>
>> 1. open vorta
>> 2. create a new profile (just enter the name and exit)
>> 3. close vorta
>> 4. SIGSEGV
>>

Sandro, thank you very much for your help with bug-hunting, much
appreciated!  :-) Given that multiple dialogues are affected, do you
think a cherry pick of the fix will meet the criteria for an unblock
exception or stable-update (possibly with the left-click noop bug, if in
fact that's Vorta-specific)?  I'd like to wait 10 days (migration to
testing delay) before cloning and retitling (or reopening) #978105,
because I don't want to give the release team reason to grumble about
why 0.7.5-1 might not be more appropriate for Buster than 0.7.1-4.

> Manu ***@***.***> writes:
>
> Right. Can reproduce it. It's a related issue and happens when the opened dialog isn't deleted properly.
>
> Deleting it when closing the app didn't work reliably, but setting `self.setAttribute(QtCore.Qt.WA_DeleteOnClose)` worked. PR: #922 This should fix it for all our dialogs.
>

Yay!  Thank you :-)  P.S. I wonder if PyQt documentation could be
improved, to help other devs avoid these pitfalls, or maybe even if PyQt
could more safely fulfill the expectations of Python devs?

Cheers,
Nicholas

**Comment by sandrotosi** [comment]
> Given that multiple dialogues are affected, do you think a cherry pick of the fix will meet the criteria for an unblock exception or stable-update (possibly with the left-click noop bug, if in fact that's Vorta-specific)?

to be extra safe, you can prepare a tentative package (without uploading it), take the debdiff and send it to an unblock request to the release team asking if that's an acceptable change, explaining its impact etc etc.

**Comment by m3nu** [comment]
Merged this latest fix. I also tried the two other dialogs we have and they didn't result in a segfault.

We attach the affected dialogs to the main window for testing. This may be the reason.

There is no real documentation on this. I learn most by looking at other similar PyQt5 projects. It also doesn't happen on macOS and not on all Linuxes. Probably some artifacts of the underlying Qt libs in use.
